# The title of your homepage
title = "Start Here"
favicon_url = "favicon.svg"

[background]
# The type of background for your homepage
# Mode			| Result
# --------------|--------------------
# triangles		| Random triangles
# static		| Static background image
mode = "triangles"

# If background.mode is set to static, this sets the background URL.
# Defaults to a random image from the "calm wallpapers" 
# Unsplash collection.
# Has no effect if background_mode isn't set to static.
# May also be an array of URLs - 1 will be picked at random from the list.
url = "https://source.unsplash.com/collection/137627/1920x1080"

[[items]]
	label = "Github"
	icon_mode = "mdi"
	icon = "mdi-github"
	link = "https://zeridon.github.com/simple-dash/"

[[items]]
	label = "Github"
	icon_mode = "mdi"
	icon = "mdi-github"
	link = "https://zeridon.github.com/simple-dash/"

[[items]]
	label = "Github"
	icon_mode = "mdi"
	icon = "mdi-github"
	link = "https://zeridon.github.com/simple-dash/"

[[items]]
	label = "Github"
	icon_mode = "mdi"
	icon = "mdi-github"
	link = "https://zeridon.github.com/simple-dash/"

[[items]]
	label = "Github"
	icon_mode = "mdi"
	icon = "mdi-github"
	link = "https://zeridon.github.com/simple-dash/"

[[items]]
	label = "Github"
	icon_mode = "mdi"
	icon = "mdi-github"
	link = "https://zeridon.github.com/simple-dash/"

[[items]]
	label = "Github"
	icon_mode = "mdi"
	icon = "mdi-github"
	link = "https://zeridon.github.com/simple-dash/"

[[items]]
	label = "Github"
	icon_mode = "mdi"
	icon = "mdi-github"
	link = "https://zeridon.github.com/simple-dash/"
